[core]
data_directory = /var/lib/openwebrx
temporary_directory = /tmp
log_level = INFO

[web]
#Uncomment address-field to bind OWRX to a specific IP-address.
#Leaving the address-field commented will bind OWRX to address 0.0.0.0 so all interfaces.
#Use 127.0.0.1 for localhost only, or any other configured address to bind to that address only.
#address = 127.0.0.1
port = 8073
ipv6 = true

[aprs]
# path to the aprs symbols repository (get it here: https://github.com/hessu/aprs-symbols)
symbols_path = /usr/share/aprs-symbols/png
